config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'salesreport/index'
  resources :loans do
    collection do
      get :loan
    end
  end

  resources :salespeople

  resources :customers

  resources :quotes do
    member do
      get 'final_price'
    end
  end

  resources :cars do
    member do
      get 'markupprice'
    end
  end

  root 'homepage#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :customer
  belongs_to :salesperson
  belongs_to :car
  has_one :loan

  validates_presence_of :salesperson_id
  validates_presence_of :customer_id
  validates_presence_of :car_id

  after_save :update_car_status
  before_save :calculate_final_price


  def update_car_status
    if self.salestatus == true
      Car.update(self.car_id, :carstatus => true)
    else
      Car.update(self.car_id, :carstatus => false)
    end

  end

  before_destroy { |record| Car.update(self.car_id, :carstatus => false)}

  def quote_info
    "#{car.model}, #{car.color}, $#{final_price.round(2)}"
  end

  def boolean_name
    salestatus ? 'Sold' : 'Unsold'
  end


  def calculate_final_price
  self.sales_tax = (self.car.markupprice * 0.043).round(2)
  self.final_price = (self.car.markupprice + self.sales_tax).round(2)
  end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def final_price
    quote = Quote.find(params[:id])
    render json: quote
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:wholesale_price, :markup_price, :sales_tax, :final_price, :salestatus, :car_id, :customer_id, :salesperson_id)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for @quote, :html => { :class => "form-horizontal"} do |f| %>
    <% if @quote.errors.any? %>
        <div id="error_explanation">
          <div class = "alert alert-danger">
            <%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:
          </div>

          <ul>
            <% @quote.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
      <legend>Fill out Quote Information</legend>
      <div class="form-group">
        <%= f.label :salesperson_id, :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.collection_select :salesperson_id, Salesperson.all, :id, :full_name,
                                  {prompt: "Select a Salesperson"}, {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :customer_id, :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.collection_select :customer_id, Customer.all, :id, :full_name,
                                  {prompt: "Select a Customer"}, {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :car_id, :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.collection_select :car_id, Car.all, :id, :car_sold,
                                  {prompt: "Select a Car"},
                                  {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :wholesale_price, 'Retail Price: ', :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.text_field :wholesale_price, :class => 'form-control', :readonly => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :markup_price, 'Markup Price: ', :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.text_field :markup_price, :class => 'form-control', :readonly => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :sales_tax, 'Sales Tax (4.3%): ',:class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.text_field :sales_tax, :class => 'form-control', :readonly => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :final_price, 'Total Price:', :class => 'col-lg-2 control-label' %><br>
        <div class="col-lg-10">
          <%= f.text_field :final_price, :class => 'form-control', :readonly => true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :salestatus, 'Sold', :class => 'col-lg-2 control-label'%><br>
        <div class="col-lg-10">
          <%= f.check_box :salestatus, :class => 'checkbox' %>
        </div>


      </div>
      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit 'Submit Quote', :class => 'btn btn-primary' %>
          <%= link_to 'Cancel',quotes_path, :class => 'btn btn-default' %>
        </div>
      </div>
    </fieldset>

<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote, :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', quotes_path, :class => 'btn btn-primary btn-sm' %>

app/views/quotes/index.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>


<h1>Customer Quotes</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Salesperson</th>
    <th>Customer</th>
    <th>Car</th>
    <th>Retail Price</th>
    <th>Markup Price</th>
    <th>Sales Tax</th>
    <th>Total Price</th>
    <th>Quote status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.salesperson.full_name %></td>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.car.car_details %></td>
        <td><%= number_to_currency(quote.wholesale_price) %></td>
        <td><%= number_to_currency(quote.markup_price) %></td>
        <td><%= number_to_currency(quote.sales_tax) %></td>
        <td><%= number_to_currency(quote.final_price) %></td>
        <td><%= quote.boolean_name %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), :class => 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => 'btn btn-danger btn-sm'%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Quote', new_quote_path, :class => 'btn btn-primary' %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Go Back', quotes_path, :class => 'btn btn-primary' %>

app/views/quotes/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<p>
  <strong>Salesperson:</strong>
  <%= @quote.salesperson.full_name %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.full_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.car_details %>
</p>

<p>
  <strong>Retail Price:</strong>
  <%= number_to_currency(@quote.wholesale_price) %>
</p>

<p>
  <strong>Markup Price:</strong>
  <%= number_to_currency(@quote.markup_price) %>
</p>

<p>
  <strong>Sales Tax (4.3%):</strong>
  <%= number_to_currency(@quote.sales_tax) %>
</p>

<p>
  <strong>Total Price:</strong>
  <%= number_to_currency(@quote.final_price) %>
</p>

<p>
  <strong>Quote status:</strong>
  <%= @quote.boolean_name %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote), :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', quotes_path, :class => 'btn btn-primary btn-sm' %>