config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'salesreport/index'
  resources :loans do
    collection do
      get :loan
    end
  end

  resources :salespeople

  resources :customers

  resources :quotes do
    member do
      get 'final_price'
    end
  end

  resources :cars do
    member do
      get 'markupprice'
    end
  end

  root 'homepage#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :phone

  def full_name
    "#{last_name}, #{first_name}"
  end

  def self.search(search)
    if search
      where('last_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.json {render json: @customers}
    if params[:search]
      @customers = Customer.search(params[:search]).order("last_name ASC, first_name ASC").paginate(page: params[:page], per_page: 10)
      if @customers.blank?
        flash.now[:alert] = "The last name does not match any record. Please try again or Create New Customer."
      end
    else
      @customers = Customer.all.order("last_name ASC, first_name ASC").paginate(page: params[:page], per_page: 10)
    end
  end
end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :address, :phone, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
        <div id="error_explanation">
          <div class = "alert alert-danger">
            <%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:
          </div>
          <ul>
            <% @customer.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <form class="form-horizontal">
      <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
              margin: 0 2px; padding: 0.35em 0.625em 0.75em;">
        <legend>Fill out Customer Information</legend>
        <div class="form-group">
          <%= f.label :last_name, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Luong' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :first_name, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'Tina' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :address, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :address, :class => 'form-control', :placeholder => '8500 Neff St. Houston, TX 77072' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :phone, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :phone, :class => 'form-control', :placeholder => '(713) 815-4996'%>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :email, :class => 'form-control', :placeholder => 'tinaluong@uh.edu' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit 'Submit', :class => 'btn btn-primary' %>
            <%= link_to 'Cancel',customers_path, :class => 'btn btn-default' %>
          </div>
        </div>
      </fieldset>
    </form>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer, :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', customers_path, :class => 'btn btn-primary btn-sm' %>

app/views/customers/index.html.erb
<%= form_tag customers_path, :html => { :class => "form-horizontal"}, :method => 'get',
             :id => "customers_search" do %>
    <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
      <legend>Enter Customer's Last Name to Search for Customer</legend>
      <%= text_field_tag :search, params[:search], :id => "filter", placeholder: "Smith" %>
      <%= submit_tag "Search", :last_name => nil, :class => 'btn btn-default btn-sm' %>
    </fieldset>

<% end %>
<center><div class = "pagination pagination-sm">
  <%= will_paginate @customers , renderer: BootstrapPagination::Rails %>
</div></center>

<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<% if alert %><p class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button><%= alert %></p><% end %>

<h1>Customers</h1>

<table class="table table-striped table-hover">
  <thead>

  <tr>
    <th>Last name</th>
    <th>First name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.last_name %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), :class => 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => 'btn btn-danger btn-sm' %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<center><div class = "pagination pagination-sm">
  <%= will_paginate @customers , renderer: BootstrapPagination::Rails %>
</div></center>
<br>


<%= link_to 'Create New Customer', new_customer_path, :class => 'btn btn-primary' %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Go Back', customers_path, :class => 'btn btn-primary' %>

app/views/customers/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<h1><%= @customer.full_name%></h1>
<hr>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer), :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', customers_path, :class => 'btn btn-primary btn-sm' %>