config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'salesreport/index'
  resources :loans do
    collection do
      get :loan
    end
  end

  resources :salespeople

  resources :customers

  resources :quotes do
    member do
      get 'final_price'
    end
  end

  resources :cars do
    member do
      get 'markupprice'
    end
  end

  root 'homepage#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :quote
  validates_presence_of :quote_id
  validates_presence_of :down_payment
  validates_presence_of :interest_rate
  #before_save :calculate_monthly_payment

  def self.calculate_loan_table(loan_amount = 0, term = 0,interest_rate = 0)
    Rails.logger.debug "Inputs: #{loan_amount} #{term} #{interest_rate}"
    payment = []
    months = (term * 12) - 1
    loan_amount = BigDecimal(loan_amount)
    interest_rate = BigDecimal(interest_rate)
    rate = interest_rate/1200
    n = rate * loan_amount
    d = 1 - (1 + rate)**-(term*12)
    monthly_payment = (n / d).round(2)
    count = 0
    (0..months).each do
      payment << count+= 1
      payment << monthly_payment
      monthly_interest = (loan_amount * rate).round(2)
      payment << monthly_interest
      monthly_principal = (monthly_payment - monthly_interest).round(2)
      payment << monthly_principal
      balance  = loan_amount -= monthly_principal
      payment << balance.round(2)
    end
    return payment
  end

  def calculate_loan_table
    return self.class.calculate_loan_table(self.loan_amount,self.term,self.interest_rate)
  end


  private
  def calculate_monthly_payment
    unless self.down_payment.blank?
      self.loan_amount = (self.quote.final_price - self.down_payment).round(2)
      r = self.interest_rate / 1200
      n = r * self.loan_amount
      d = 1 - (1 + r)**-((self.loan_term.term * 12))
      self.monthly_payment = (n / d).round(2)
    end
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
    @loan_array = @loan.calculate_loan_table
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def loan
    loan_amount = params[:loan_amount]
    term = params[:term]
    interest_rate = params[:interest_rate]
    @loan_array = Loan.calculate_loan_table(loan_amount.to_d, term.to_i, interest_rate.to_d)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:down_payment, :loan_amount, :term, :interest_rate, :monthly_payment, :quote_id)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
  def loan_term
    [
        ['3'], ['4'], ['5']
    ]
  end
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
    <% if @loan.errors.any? %>
        <div id="error_explanation">
          <div class = "alert alert-danger">
            <%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:
          </div>
          <ul>
            <% @loan.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <form class="form-horizontal">
      <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
              margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
        <legend>Fill out Loan Information</legend>
        <div class="form-group">
          <%= f.label :quote_id, :class => 'col-lg-2 control-label', :for => 'select' %><br>
          <div class="col-lg-10">
            <%= f.collection_select :quote_id, Quote.all, :id, :quote_info,
                                    {prompt: "Select a quote", selected: "get_current_final_price_or_nil"},
                                    {class: "form-control"}%>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :down_payment, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :down_payment, :class => 'form-control', :placeholder => '2000' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :loan_amount, 'Principal Balance', :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :loan_amount, :class => 'form-control', :readonly => true %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :term, 'Loan term (in years)', :class => 'col-lg-2 control-label'%><br>
          <div class="col-lg-10">
            <%= f.select :term, options_for_select(loan_term),
                                    {prompt: "Select a term"},
                                    {class: "form-control"} %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :interest_rate, 'Interest rate (%)', :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :interest_rate, :class => 'form-control', :placeholder => '1.5' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :monthly_payment, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :monthly_payment, :class => 'form-control', :readonly => true %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit 'Submit Loan', :class => 'btn btn-primary' %>
            <%= link_to 'Cancel',loans_path, :class => 'btn btn-default' %>
          </div>
        </div>
      </fieldset>
    </form>
    <!-- Table will be inserted here -->
    <div id="loan-table" class="table-format"></div>
<% end %>

app/views/loans/_loan_table.html.erb
<h2>Amortization Schedule</h2>
<table class="table table-striped table-hover">
  <th>Month</th>
  <th>Payment</th>
  <th>Interest</th>
  <th>Principal</th>
  <th>Loan Balance</th>
  <% @loan_array.each_slice(5) do |p|  %>
      <tr class="info">
        <% p.each do |a| %>
            <td> <%= a %></td>
        <% end %>
  <% end %>

</table>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan, :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', loans_path, :class => 'btn btn-primary btn-sm' %>

app/views/loans/index.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<h1>Loans</h1>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Car Price</th>
    <th>Down Payment</th>
    <th>Principal Balance</th>
    <th>Loan Term (years)</th>
    <th>Interest Rate (%)</th>
    <th>Monthly Payment</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @loans.each do |loan| %>
      <tr>
        <td><%= loan.quote.quote_info %></td>
        <td><%= number_to_currency(loan.down_payment) %></td>
        <td><%= number_to_currency(loan.loan_amount) %></td>
        <td><%= loan.term %></td>
        <td><%= number_to_percentage(loan.interest_rate, precision: 2) %></td>
        <td><%= number_to_currency(loan.monthly_payment) %></td>
        <td><%= link_to 'Show', loan, :class => 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan), :class => 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Delete', loan, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => 'btn btn-danger btn-sm'%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create New Loan', new_loan_path, :class => 'btn btn-primary' %>

app/views/loans/loan.js.erb
$('#loan-table').html("<%= j (render 'loan_table') %>")

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Go Back', loans_path, :class => 'btn btn-primary' %>

app/views/loans/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<p>
  <strong>Car Price:</strong>
  <%= @loan.quote.quote_info %>
</p>

<p>
  <strong>Down payment:</strong>
  <%= number_to_currency(@loan.down_payment) %>
</p>

<p>
  <strong>Loan amount:</strong>
  <%= number_to_currency(@loan.loan_amount) %>
</p>

<p>
  <strong>Loan term (years):</strong>
  <%= @loan.term %>
</p>

<p>
  <strong>Interest rate (%):</strong>
  <%= number_to_percentage((@loan.interest_rate), precision: 2) %>
</p>

<p>
  <strong>Monthly payment:</strong>
  <%= number_to_currency(@loan.monthly_payment) %>
</p>

<%= render 'loan_table' %>

<%= link_to 'Edit', edit_loan_path(@loan), :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', loans_path, :class => 'btn btn-primary btn-sm' %>