config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  get 'salesreport/index'
  resources :loans do
    collection do
      get :loan
    end
  end

  resources :salespeople

  resources :customers

  resources :quotes do
    member do
      get 'final_price'
    end
  end

  resources :cars do
    member do
      get 'markupprice'
    end
  end

  root 'homepage#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes
  validates_presence_of :model
  validates_presence_of :color
  validates_presence_of :vin
  validates_presence_of :retailprice
  before_save :calculate_markup

  def self.search(search)
    if search
      where('model LIKE ? OR color LIKE ? OR vin LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end

  def boolean_name
    carstatus ? 'Sold' : 'Unsold'
  end

  def car_details
    "#{model} #{color}"
  end

  def car_sold
    "#{model} #{color}, #{boolean_name}"
  end

  private
  def calculate_markup
   self.markupprice = retailprice + (retailprice * 0.1)
  end


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @Cars = Car.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html
      format.json {render json: @cars}

    if params[:search_car]
      @cars = Car.search(params[:search_car]).order("model ASC, color ASC, vin ASC").paginate(page: params[:page], per_page: 10)
      if @cars.blank?
        flash.now[:alert] = "Your search does not match any record. Please try again or Create New Car."
      end
    else
      @cars = Car.all.order("model ASC, color ASC, vin ASC").paginate(page: params[:page], per_page: 10)
    end
  end
end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def markupprice
    car = Car.find(params[:id])
    render json: car
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :color, :vin, :retailprice, :markupprice, :carstatus)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
    <% if @car.errors.any? %>
        <div id="error_explanation">
          <div class = "alert alert-danger">
            <%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:
          </div>
          <ul>
            <% @car.errors.full_messages.each do |message| %>
                <li class="alert alert-danger"><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <form class="form-horizontal">
      <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
              margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
        <legend>Fill out Car Information</legend>
        <div class="form-group">
          <%= f.label :model, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :model, :class => 'form-control', :placeholder => 'Coupe Lexus RC 350' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :color, :class => 'col-lg-2 control-label'%><br>
          <div class="col-lg-10">
            <%= f.text_field :color, :class => 'form-control', :placeholder => 'White' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :vin, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :vin, :class => 'form-control', :placeholder => '17-digit VIN code' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :retailprice, :class => 'col-lg-2 control-label' %><br>
          <div class="col-lg-10">
            <%= f.text_field :retailprice, :class => 'form-control', :placeholder => '35000' %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :carstatus, 'Sold', :class => 'col-lg-2 control-label'%><br>
          <div class="col-lg-10">
            <%= f.check_box :carstatus, :class => 'checkbox' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
            <%= f.submit 'Submit', :class => 'btn btn-primary' %>
            <%= link_to 'Cancel',cars_path, :class => 'btn btn-default' %>
          </div>
        </div>
      </fieldset>
    </form>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car, :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', cars_path, :class => 'btn btn-primary btn-sm' %>

app/views/cars/index.html.erb
<%= form_tag cars_path, :html => { :class => "form-horizontal"}, :method => 'get', :id => "search_car" do %>
    <fieldset style="background-color: #f8f5f0; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
      <legend>Enter Model, Color, or VIN to Search for Car</legend>
      <%= text_field_tag :search_car, params[:search_car], placeholder: "Lexus IS 250", :id => 'search_field' %>
      <%= submit_tag "Search", :model => nil, :color =>  nil, :vin => nil, :class => 'btn btn-default  btn-sm' %>
    </fieldset>
<% end %>

<center><div class = "pagination pagination-sm">
  <%= will_paginate @cars , renderer: BootstrapPagination::Rails %>
</div></center>
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<% if alert %><p class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button><%= alert %></p><% end %>

<h1>Cars Inventory</h1>

<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Model</th>
    <th>Color</th>
    <th>VIN</th>
    <th>Retail Price</th>
    <th>Markup Price</th>
    <th>Car Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.retailprice) %></td>
        <td><%= number_to_currency(car.markupprice) %></td>
        <td><%= car.boolean_name %></td>
        <td><%= link_to 'Edit', edit_car_path(car), :class => 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => 'btn btn-danger btn-sm' %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<center><div class = "pagination pagination-sm">
  <%= will_paginate @cars , renderer: BootstrapPagination::Rails %>
</div></center>

<br>

<%= link_to 'Create New Car', new_car_path, :class => 'btn btn-primary' %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Go Back', cars_path, :class => 'btn btn-primary' %>

app/views/cars/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Retailprice:</strong>
  <%= number_to_currency(@car.retailprice) %>
</p>

<p>
  <strong>Markupprice:</strong>
  <%= number_to_currency(@car.markupprice) %>
</p>

<p>
  <strong>Carstatus:</strong>
  <%= @car.boolean_name %>
</p>

<%= link_to 'Edit', edit_car_path(@car), :class => 'btn btn-primary btn-sm' %> |
<%= link_to 'Go Back', cars_path, :class => 'btn btn-primary btn-sm' %>